# Generated by Django 5.0.4 on 2024-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7),
        ),
    ]
